name: Update Linear Ticket

on:
  pull_request:
    types: [opened, reopened, closed]
  push:
      branches:
        - main

jobs:
  update-linear:
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR Title
        id: extract_title
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Parse Linear Issue ID
        id: parse
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ([A-Z]+-[0-9]+) ]]; then
            echo "Found Linear Issue ID: ${BASH_REMATCH[1]}"
            echo "ISSUE_ID=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "No Linear issue ID found"
            exit 0
          fi
        shell: bash

      - name: Print Issue ID
        run: echo "Issue ID is $ISSUE_ID"
      - name: Query Issue from Linear
        run: |
            API_KEY="${{ secrets.LINEAR_API_KEY }}"
            ISSUE_ID="MOBI-3935"
            LINEAR_API_URL="https://api.linear.app/graphql"
            
            read -r -d '' GRAPHQL_QUERY <<EOF
            {
              "query": "query Issue { issue(id: \\\"$ISSUE_ID\\\") { id title description } }"
            }
     
      
